### ISSUE TITLE
私のリポジトリ paywaysのforkに関して

### ISSUE THREAD

**Issue by Teppeichang** [mii6412/oiwai_app#1]
はじめまして。
表題のリポジトリ作成者の鳥居です。

早速で恐縮ですが一点お聞きしたいことがございます。
テックキャンプ受講生でポートフォリオ作成中と見受けますが、私のリポジトリをforkされた意図は何でしょうか？

**Comment by mii6412** [comment]
Readme作成にあたり何人かの方ののReadmeを拝見させていただいている中で誤操作によりコピーしてしまったものと思われます。
ご指摘いただくまで気付きませんでした。
すでに私のページからは削除しておりますのでご安心ください。
この度はご不快を招き申し訳ありませんでした。

**Comment by Teppeichang** [comment]
お返事ありがとうございます。ご参考にしていただき光栄です！
forkだとリポジトリが操作できてしまい、怖頂く部分があるので参考にされる場合はcloneしてた頂く方が良いかと思います。
懸念事項は解決したんで、このissueはcloseさせていただきますね。
